export const employees = [
  [
    {
      id: 1,
      name: "Aino Virtanen",
      title: "HR Manager",
      salary: 4200,
      phone: "040-1234567",
      email: "aino.virtanen@example.com",
      animal: "Owl",
      startDate: "2018-04-01",
      location: "Helsinki",
      department: "Human Resources",
      skills: ["Recruiting", "Communication", "Employee Relations"],
    },
    {
      id: 2,
      name: "Lars Johansson",
      title: "Finance Manager",
      salary: 5000,
      phone: "040-2345678",
      email: "lars.johansson@example.com",
      animal: "Lion",
      startDate: "2025-03-15",
      location: "Stockholm",
      department: "Finance",
      skills: ["Financial Planning", "Budgeting", "Analysis"],
    },
    {
      id: 3,
      name: "Mikko Kallio",
      title: "Marketing Director",
      salary: 5500,
      phone: "040-3456789",
      email: "mikko.kallio@example.com",
      animal: "Eagle",
      startDate: "2019-06-20",
      location: "Helsinki",
      department: "Marketing",
      skills: ["Brand Strategy", "Digital Marketing", "SEO"],
    },
    {
      id: 4,
      name: "Sofia Lehtinen",
      title: "Sales Manager",
      salary: 4600,
      phone: "040-4567890",
      email: "sofia.lehtinen@example.com",
      animal: "Dolphin",
      startDate: "2017-02-10",
      location: "Helsinki",
      department: "Sales",
      skills: ["Sales Strategy", "Customer Relationship", "Negotiation"],
    }, 
    {
      
      id: 5,
      name: "Jani Rautio",
      title: "IT Specialist",
      salary: 4200,
      phone: "040-5678901",
      email: "jani.rautio@example.com",
      animal: "Tiger",
      startDate: "2020-09-01",
      location: "Tampere",
      department: "IT",
      skills: ["Software Development", "Networking", "Security"],
    },
    {
      id: 6,
      name: "Elina Mikkola",
      title: "Project Manager",
      salary: 4800,
      phone: "040-6789012",
      email: "elina.mikkola@example.com",
      animal: "Bear",
      startDate: "2015-12-05",
      location: "Espoo",
      department: "Project Management",
      skills: ["Project Planning", "Risk Management", "Team Leadership"],
    },
    {
      id: 7,
      name: "Antti Niemi",
      title: "Product Manager",
      salary: 5200,
      phone: "040-7890123",
      email: "antti.niemi@example.com",
      animal: "Wolf",
      startDate: "2018-03-22",
      location: "Helsinki",
      department: "Product Development",
      skills: ["Product Lifecycle", "Market Research", "Product Launch"],
    },
    {
      id: 8,
      name: "Tiina Korhonen",
      title: "Customer Service Manager",
      salary: 4500,
      phone: "040-8901234",
      email: "tiina.korhonen@example.com",
      animal: "Rabbit",
      startDate: "2019-05-16",
      location: "Tampere",
      department: "Customer Service",
      skills: ["Customer Support", "Problem Solving", "Communication"],
    },
    {
      id: 9,
      name: "Jukka Hämäläinen",
      title: "Legal Advisor",
      salary: 6000,
      phone: "040-9012345",
      email: "jukka.hamalainen@example.com",
      animal: "Elephant",
      startDate: "2016-11-10",
      location: "Helsinki",
      department: "Legal",
      skills: ["Contract Law", "Legal Consulting", "Litigation"],
    },
    {
      id: 10,
      name: "Kati Salonen",
      title: "Operations Manager",
      salary: 5500,
      phone: "040-0123456",
      email: "kati.salonen@example.com",
      animal: "Fox",
      startDate: "2017-01-23",
      location: "Helsinki",
      department: "Operations",
      skills: ["Process Optimization", "Supply Chain", "Logistics"],
    },
    {
      id: 11,
      name: "Ville Koskinen",
      title: "Business Analyst",
      salary: 4900,
      phone: "040-1239876",
      email: "ville.koskinen@example.com",
      animal: "Hawk",
      startDate: "2024-10-30",
      location: "Helsinki",
      department: "Business Analysis",
      skills: ["Data Analysis", "Business Strategy", "Market Research"],
    },
    {
      id: 12,
      name: "Nina Ojala",
      title: "HR Specialist",
      salary: 4300,
      phone: "040-2348765",
      email: "nina.ojala@example.com",
      animal: "Swan",
      startDate: "2010-08-25",
      location: "Tampere",
      department: "Human Resources",
      skills: ["Recruitment", "Employee Engagement", "Training"],
    },
    {
      id: 13,
      name: "Paavo Rinne",
      title: "Supply Chain Manager",
      salary: 5700,
      phone: "040-3457654",
      email: "paavo.rinne@example.com",
      animal: "Cheetah",
      startDate: "2016-04-10",
      location: "Helsinki",
      department: "Supply Chain",
      skills: ["Logistics", "Inventory Management", "Vendor Relations"],
    },
    {
      id: 14,
      name: "Laura Leino",
      title: "Quality Assurance Specialist",
      salary: 4600,
      phone: "040-4564321",
      email: "laura.leino@example.com",
      animal: "Panther",
      startDate: "2025-02-11",
      location: "Tampere",
      department: "Quality Assurance",
      skills: ["Quality Control", "Testing", "Process Improvement"],
    },
    {
      id: 15,
      name: "Tomi Virtanen",
      title: "Software Engineer",
      salary: 5500,
      phone: "040-5671234",
      email: "tomi.virtanen@example.com",
      animal: "Cat",
      startDate: "2000-11-12",
      location: "Helsinki",
      department: "Engineering",
      skills: ["Java", "Python", "Software Development"],
    },
  ],
];
