import finance from "./DepartmentImages/finance.jpg";
import supplyChain from "./DepartmentImages/supplyChain.jpg";
import marketing from "./DepartmentImages/marketing.jpg";
import sales from "./DepartmentImages/sales.jpg";
import it from "./DepartmentImages/it.jpg";
import projectManagement from "./DepartmentImages/projectManagement.jpg";
import productDevelopment from "./DepartmentImages/productDevelopment.jpg";
import customerService from "./DepartmentImages/customerService.jpg";
import legal from "./DepartmentImages/legal.jpg";
import businessAnalysis from "./DepartmentImages/businessAnalysis.jpg";
import qualityAssurance from "./DepartmentImages/qualityAssurance.jpg";
import defaultImg from "./DepartmentImages/default.jpg";
import humanResources from "./DepartmentImages/humanResources.jpg";
const GetDepartmentImage = (department) => {
    if (department === "Human Resource Management") return humanResources;
    if (department === "Finance") return finance;
    if (department === "Supply Chain") return supplyChain;
    if (department === "Marketing") return marketing;
    if (department === "Sales") return sales;
    if (department === "IT") return it;
    if (department === "Project Management") return projectManagement;
    if (department === "Product Development") return productDevelopment;
    if (department === "Customer Service") return customerService;
    if (department === "Legal") return legal;
    if (department === "Business Analysis") return businessAnalysis;
    if (department === "Quality Assurance") return qualityAssurance;
    return defaultImg;
};

export default GetDepartmentImage;
